### ISSUE TITLE
Refactor TODO

### ISSUE THREAD

**Issue by bmathews** [bmathews/playback#1]
**MVP**
- [x] Add subtitle support
  - [x] HTML5Video
  - [x] Chromecast
- [x] Split out loaders (ipfs untested) 
- [x] Refresh cast devices when opening dialog
- [x] Load files via drag and drop
- [x] Load subtitles via drag and drop
- [x] Load files via url paste
- [x] Preventsleep while playing
- [x] Timeline seek tooltips
- [x] Hide ui on mouseidle
- [x] Ellipsis playlist track titles
- [x] Double click player to pause/resume
- [x] Spacebar/etc to pause/resume
- [x] Hotkeys for fullscreen
- [x] Context menu
- [x] App menu
- [ ] Chromecast error handling
- [x] Volume control
  - [x] Ensure volume is set/used onload
  - [x] Ensure mute is set/used onload
- [x] Follow functionality
  - [ ] Improve follow UI (e.g., disable all controls?)
- [x] Indicate muted status
- [ ] Chromecast support
  - [x] volume
  - [ ] mute (chromecasts lib can't unmute)
  - [x] end
  - [x] metadata
- [x] HTML support
  - [x] volume
  - [x] mute
  - [x] end
  - [x] metadata
  - [x] resizing
- [x] Switch between players seamlessly
- [x] Fix youtube quality detection/selection
- [ ] Ensure package bundling works
  - [x] OSX
  - [ ] Windows

**ideal**
- [x] Subtitle on/off controls
- [ ] Ensure subtitle state is consistent when switching between tracks in queue 
- [ ] Subtitle selection/loading via UI
- [x] UI buttons for removing items from playlist
- [x] Transparent frame with custom titlebar
- [x] Drag window around by video
- [x] Empty state for chromecast dialog
- [x] Empy state for playlist dialog
- [x] Improve timeline seeking animations

**bonus**
- [x] Respond to media keys
- [ ] Restrict attempts at loading of files to known file types? http://www.chromium.org/audio-video
- [ ] Settings dialog
  - [ ] Filters
  - [ ] Autoload subtitles
  - [ ] Resize onload of video metadata
  - [ ] Youtube quality control
  - [ ] Default player
  - [ ] Enable/disable media keys
- [ ] Indicate speed for torrents/youtube
- [x] Buffer indications
- [x] WebChimera support
  - [x] volume
  - [x] mute
  - [x] end
  - [x] metadata
  - [x] resizing

**Comment by bmathews** [comment]
@mafintosh :wave:

Here's some of the work I've been doing to clean up the UI and split out the server/playlist into electron's main process, and add support for webchimera. There are lots of small improvements that improve stability for things like switching between chromecasts and local players, playlist behaviors, and much more.

Let me know what your thoughts are regarding this and then I can get it ready for a PR. 

Code is on this branch:
https://github.com/bmathews/playback/tree/refactor-chimera-rebase

![image](https://cloud.githubusercontent.com/assets/848347/12523036/1a54d226-c109-11e5-8180-12fd8e20ebaf.png)

![image](https://cloud.githubusercontent.com/assets/848347/12523042/1ff4e72a-c109-11e5-8a82-c175c4817ad7.png)

![image](https://cloud.githubusercontent.com/assets/848347/12523054/2bfcf6a2-c109-11e5-9ae5-85dfb512c0ce.png)

![image](https://cloud.githubusercontent.com/assets/848347/12533890/d21e16ea-c1f6-11e5-8d85-179c2f56a654.png)

**Comment by mafintosh** [comment]
WHOOOOOOOAH THAT LOOKS AWESOME

**Comment by mafintosh** [comment]
not sure how much it'll offend @maxogden if we remove the intro cat though

**Comment by Kamahl19** [comment]
Great job @bmathews ! Few days ago I have experimented with AirPlay and I have made mafintosh's version working with XBMC AirPlay. I want to make it work with AppleTV too. I will gladly contribute with these features to this rewrite, once it is a bit stable or when I get it running. I was not able to run chimera-rebase on Win x64 (appearently some problem with 32 bit version of VLC libs on 64bit system).

**Comment by bmathews** [comment]
@Kamahl19, awesome! I'm hoping it's easy to add airplay support to this with the way the "players" have been split up. 

Maybe you already looked and tried, but wcjs-prebuilt should work on Windows,. You might have to expiriment with the env variables during install? https://github.com/Ivshti/wcjs-prebuilt

**Comment by Kamahl19** [comment]
@bmathews It will be much easier to add it to yours refactored app, the old one is quite a mess :D But still a nice piece of software. 

Yea, I did this but it did not help
SET WCJS_PLATFORM=win && SET WCJS_ARCH=x64 && SET WCJS_RUNTIME=electron && npm i wcjs-prebuilt

I suppose you are on Mac

**Comment by bmathews** [comment]
@Kamahl19 Hm, bummer. I am on a mac, yeah.

To get it to run in the meantime, you should be able to comment out the `import WebChimera` in `app/front/UI.jsx` and where it's instantiated in the UI's constructor at line 63. Then at line 54 of `app.js`, set it to use `controller.PLAYER_HTML` as the default instead. 

I'll see if I can get a windows machine set up in the near future to try to troubleshoot that more.

**Comment by max-mapper** [comment]
im ok as long as the cat is incorporated in the drag/drop (as it is in the mock up)

**Comment by max-mapper** [comment]
oh also, that cat gif is unlicensed, we should probably switch to one of my cat photos (public domain) https://www.flickr.com/photos/catmapper/albums/72157662462294366

**Comment by mafintosh** [comment]
i bet @watson could make airplay work

**Comment by bmathews** [comment]
@mafintosh Just trying to get webchimera to work when packaging as a mac app, then I'll work on trying to get webchimera on windows, then I'll submit a PR.

**Comment by RSATom** [comment]
@bmathews, I've managed to setup prebuilt for `WebChimera.js` with embedded VLC binaries. Maybe it could be useful to you since `wcjs-prebuilt` is too unstable atm.
https://github.com/RSATom/WebChimera.js/releases
